server:
  port: 8848

wayhome:
  secretKey: 9c37e7ac39aefd941f3fad898d4105b0

spring:
  datasource:
    url: jdbc:mysql://wayhome.zhangtory.com:3306/wayhome?useUnicode=true&characterEncording=utf-8&useSSL=true
    username: zyy
    password: nobodycanstopme
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
