spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wayhome
    password: 123456
    url: jdbc:mysql://222.209.233.79/:3306/dbName?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 192.168.31.50
    pool: 6379
    timeout: 5000
    database: 0