spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wayhome?useUnicode=true&characterEncording=utf-8&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    pool: 6379
    timeout: 5000
    database: 0
